'use client';

import { useState } from 'react';
import FAQSection from '@/components/FAQSection';
import RelatedTools from '@/components/RelatedTools';
import ToolContainer from '@/components/ToolContainer';
import ToolHero from '@/components/ToolHero';

export default function RobotsTxtGeneratorPage() {
  const [sitemapUrl, setSitemapUrl] = useState('');
  const [disallowPaths, setDisallowPaths] = useState('');
  const [allowPaths, setAllowPaths] = useState('');
  const [crawlDelay, setCrawlDelay] = useState('');
  const [robotsTxt, setRobotsTxt] = useState('');

  const generateRobotsTxt = () => {
    let content = '# Robots.txt generated by ToolForFree.com\n\n';
    content += 'User-agent: *\n';

    if (allowPaths) {
      allowPaths.split('\n').forEach((path) => {
        if (path.trim()) {
          content += `Allow: ${path.trim()}\n`;
        }
      });
    }

    if (disallowPaths) {
      disallowPaths.split('\n').forEach((path) => {
        if (path.trim()) {
          content += `Disallow: ${path.trim()}\n`;
        }
      });
    } else {
      content += 'Disallow:\n';
    }

    if (crawlDelay) {
      content += `\nCrawl-delay: ${crawlDelay}\n`;
    }

    if (sitemapUrl) {
      content += `\nSitemap: ${sitemapUrl}\n`;
    }

    setRobotsTxt(content);
  };

  const downloadFile = () => {
    const blob = new Blob([robotsTxt], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main className="bg-white pb-16">
      <ToolHero
        icon="🤖"
        title="Robots.txt Generator"
        description="Generate a robots.txt file to control how search engines crawl your website. Easy to configure and download."
      />

      <ToolContainer title="Configure Robots.txt">
        <div className="space-y-6">
          <div>
            <label className="block text-sm font-semibold text-slate-900 mb-2">
              Sitemap URL (optional)
            </label>
            <input
              type="url"
              value={sitemapUrl}
              onChange={(e) => setSitemapUrl(e.target.value)}
              placeholder="https://example.com/sitemap.xml"
              className="w-full rounded-xl border border-slate-300 px-4 py-3 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <div>
            <label className="block text-sm font-semibold text-slate-900 mb-2">
              Disallow Paths (one per line)
            </label>
            <textarea
              value={disallowPaths}
              onChange={(e) => setDisallowPaths(e.target.value)}
              placeholder="/admin/&#10;/private/&#10;/temp/"
              className="w-full h-32 rounded-xl border border-slate-300 px-4 py-3 font-mono text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <div>
            <label className="block text-sm font-semibold text-slate-900 mb-2">
              Allow Paths (one per line, optional)
            </label>
            <textarea
              value={allowPaths}
              onChange={(e) => setAllowPaths(e.target.value)}
              placeholder="/public/&#10;/images/"
              className="w-full h-24 rounded-xl border border-slate-300 px-4 py-3 font-mono text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <div>
            <label className="block text-sm font-semibold text-slate-900 mb-2">
              Crawl Delay (seconds, optional)
            </label>
            <input
              type="number"
              value={crawlDelay}
              onChange={(e) => setCrawlDelay(e.target.value)}
              placeholder="1"
              className="w-full rounded-xl border border-slate-300 px-4 py-3 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <button
            onClick={generateRobotsTxt}
            className="w-full rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white transition-colors hover:bg-blue-700"
          >
            Generate Robots.txt
          </button>

          {robotsTxt && (
            <>
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-sm font-semibold text-slate-900">Generated File</label>
                  <button
                    onClick={downloadFile}
                    className="rounded-lg bg-green-600 px-4 py-2 text-sm font-semibold text-white hover:bg-green-700"
                  >
                    Download
                  </button>
                </div>
                <textarea
                  value={robotsTxt}
                  readOnly
                  className="w-full h-64 rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 font-mono text-sm"
                />
              </div>
            </>
          )}
        </div>
      </ToolContainer>

      <ToolContainer title="Features">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
            <h3 className="font-semibold text-slate-900">🎯 SEO Control</h3>
            <p className="mt-2 text-sm text-slate-600">Control crawler behavior</p>
          </div>
          <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
            <h3 className="font-semibold text-slate-900">⚡ Quick Setup</h3>
            <p className="mt-2 text-sm text-slate-600">Generate in seconds</p>
          </div>
          <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
            <h3 className="font-semibold text-slate-900">📥 Download Ready</h3>
            <p className="mt-2 text-sm text-slate-600">Save directly to file</p>
          </div>
        </div>
      </ToolContainer>

      <ToolContainer title="How To Use">
        <ol className="list-decimal space-y-2 pl-5 text-sm text-slate-700">
          <li>Enter your sitemap URL</li>
          <li>List paths to block (disallow)</li>
          <li>Optionally specify allowed paths</li>
          <li>Set crawl delay if needed</li>
          <li>Click "Generate" and download</li>
          <li>Upload to website root directory</li>
        </ol>
      </ToolContainer>

      <FAQSection
        items={[
          {
            question: 'What is robots.txt?',
            answer: 'Robots.txt is a file that tells search engines which parts of your site they can and cannot crawl.'
          },
          {
            question: 'Where should I place robots.txt?',
            answer: 'Place it in the root directory of your website (e.g., https://example.com/robots.txt).'
          },
          {
            question: 'What is crawl delay?',
            answer: 'Crawl delay tells search engines to wait a specified number of seconds between requests to your server.'
          },
          {
            question: 'Can I block specific bots?',
            answer: 'Yes, but this generator uses User-agent: * to apply rules to all bots. You can edit the file to target specific bots.'
          }
        ]}
      />

      <RelatedTools
        tools={[
          { name: 'Sitemap Generator', slug: 'sitemap-generator', icon: '🗺️' },
          { name: 'Meta Tag Generator', slug: 'meta-tag-generator', icon: '🏷️' },
          { name: 'Open Graph Generator', slug: 'open-graph-generator', icon: '📱' }
        ]}
      />
    </main>
  );
}
